language: java
sudo: false
script: mvn -DargLine="-DdatabaseEngine=h2" clean verify
notifications:
  email: false
  
notifications:
  slack: acaddemict:knomGpitG9iKLNW1chhOZQhw
  
cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
